### ISSUE TITLE
python program can't run

### ISSUE THREAD

**Issue by yybjy** [PawanOsman/PyGPT#10]

**Comment by XueMeijing** [comment]
For this line ```chat_gpt = PyGPT('eyJhbGciOiJkaXIiLCJlbmMiOiJBMR0NN....')``` , you should use your own chatGPT session,  [how to get ur own session](https://github.com/XueMeijing/dingtalk-chatgpt-bot/blob/main/config.py)

Besides, in my experience, if u want to get a chatGPT acount, you can try https://sms-activate.org/cn/rent, and then use system proxy vpn to avoid cloudflare detection

**Comment by XueMeijing** [comment]
or u can try this repo https://github.com/PawanOsman/ChatGPT, which doesn't need chatgpt account

**Comment by yybjy** [comment]
兄弟我昨天更改了我的那个sesstoken,昨天还能用，我今天刷新了一下那个sesstoken,结果就不能用了，一直提示我conservationid错误
![屏幕截图 2023-02-07 134946](https://user-images.githubusercontent.com/91821567/217160288-425b3f8f-35ce-4016-ac1b-f8d94f376311.png)

**Comment by yybjy** [comment]
这个该怎么办，大佬快救命啊！！！！万分感谢啊
