### ISSUE TITLE
Disconnected from server

### ISSUE THREAD

**Issue by 0xCodeGuruX** [PawanOsman/PyGPT#11]
I used `__Secure-next-auth.session-token`, but I can't connect to the server, and my proxy is working fine. Not ChatGPT Plus btw. 
```
Connected to server
Ready!!
The capital of France is Paris.
Disconnected from server
```

**Comment by yybjy** [comment]
> 我使用了 ，但我无法连接到服务器，并且我的代理工作正常。不是聊天GPT加顺便说一句。`__Secure-next-auth.session-token`
> 
> ```
> Connected to server
> Ready!!
> The capital of France is Paris.
> Disconnected from server
> ```
ready那里表示你已经连接上了，并且给出了回答首都是巴黎，后面那个代表断开链接，是他代码里面的那个disconnect执行了断开
