### ISSUE TITLE
Is there someone met the error ModuleNotFoundError: No module named 'PyGPT'?

### ISSUE THREAD

**Issue by XueMeijing** [PawanOsman/PyGPT#6]
Hi,
I installed PyGPT by pip3 install --upgrade PyGPT, and it is indeed appeared in pip3 list. But i cant import it. Im not python dev, so im not sure it was my PC's problem or PyGPT problem. By the way, other packages works normal. The same occurred on my google cloud platform instance.

**Comment by PawanOsman** [comment]
Can you provide more information?
Specifically, what is the operating system of your server and what command are you using to run your Python script?
Additionally, we also have packages available for NodeJS and C#,
so if you are familiar with one of those languages, it may be beneficial to use them instead.

**Comment by XueMeijing** [comment]
However, i copyed PyGPT/src/pygpt.py file to local project and it works very well. I searched many GPT repos but it seems that PyGPT is the fast and the easiest. But i dont know how bypass_node works. Would you mind introduce some info on  it?

**Comment by PawanOsman** [comment]
I apologize, but I am unable to discuss the bypass servers as we wish to prevent them from being patched by OpenAI.

**Comment by XueMeijing** [comment]
> 

My pc system is macOS Big Sur, and the server instance is  Debian 10.2.1-6. i just  pip3 install --upgrade PyGPT, and copy the example  on README.md, and python3 example.py, then the error occured. I've reinstalled and it was all the same. yeah i have  seen  NodeJS and C# packages,  I'll have a try on NodeJS latter. Thanks for your work very much

**Comment by XueMeijing** [comment]
> I apologize, but I am unable to discuss the bypass servers as we wish to prevent them from being patched by OpenAI.
> 
> 我很抱歉，但我不能讨论旁路服务器，因为我们希望阻止他们被 OpenAI 修补。

Got it, thank you all the same~

**Comment by PawanOsman** [comment]
> 

you can also use this command to install it
```bash
python3 -m pip install --upgrade PyGPT
```
np

**Comment by XueMeijing** [comment]
Hi PawanOsman,
I found that after install PyGPT, the folder shows that the package changed  to pygpt.py. And beacuse of the python is case sensitive, so that was why i cant import it. After i changed to ```from pygpt import PyGPT``` it works well.
Here is the screenshot

![image](https://user-images.githubusercontent.com/35559153/212001808-1e2e61cf-3441-4f8a-8638-8519b4ac332c.png)


EDIT: all right, ```from PyGPT import PyGPT```can still work now, i dont know why.

**Comment by XueMeijing** [comment]
damn it, the screenshot seemed cant load correctly

![image](https://user-images.githubusercontent.com/35559153/212002401-2535b7b5-fd9a-4b32-a3d2-138cf73d8c29.png)
