### ISSUE TITLE
That model doesn't exist

### ISSUE THREAD

**Issue by XueMeijing** [PawanOsman/PyGPT#9]
I found that the web GPT model changed into ```text-moderation-playground``` now, it seems that it was ```text-davinci-002-render``` before. Maybe this?

![image](https://user-images.githubusercontent.com/35559153/216243961-45dc5e48-bbbc-4663-ad59-484e93a5aabb.png)
![image](https://user-images.githubusercontent.com/35559153/216244311-f71077f0-b09a-49a3-99f2-2147c2310f1d.png)

**Comment by XueMeijing** [comment]
Or maybe this ?
https://github.com/wong2/chatgpt-google-extension/issues/219

**Comment by XueMeijing** [comment]
confirmed, change model to ```text-davinci-002-render-next```can solve it

**Comment by Huhahhh** [comment]
兄弟，网页版报这个错怎么解决啊

**Comment by Huhahhh** [comment]
兄弟，网页版报这个错怎么解决啊

**Comment by XueMeijing** [comment]
> 兄弟，网页版报这个错怎么解决啊

刚才看作者已经修复了，作者用socket搞得，我们用的他的代理服务器，只能他那边修改

**Comment by XueMeijing** [comment]
> 兄弟，网页版报这个错怎么解决啊

原官网的是正常的啊，有的话应该刷新页面就好了吧

**Comment by XueMeijing** [comment]
It works normal now, thank u ~
